### ISSUE TITLE
why Squirrel.Mac framework is differ from the Squirrel.Mac official repo?

### ISSUE THREAD

**Issue by sunuslee** [electron/electron-frameworks#2]
hi,
   i noticed the file from https://github.com/electron/electron-frameworks/releases/download/v1.2.0/Squirrel.zip   in page https://github.com/electron/electron-frameworks/releases is **304k**.(v1.2.0)
   but i went to the official Squirrel.Mac repo,https://github.com/Squirrel/Squirrel.Mac/releases , the first one, https://github.com/Squirrel/Squirrel.Mac/releases/download/0.3.0/Squirrel.framework.zip  is **1.14MB**.  
  so, what's the difference between ? which one is the latest one ? thank you!

**Comment by zeke** [comment]
I bet @joshaber would know.

**Comment by joshaber** [comment]
The official Squirrel.Mac release at https://github.com/Squirrel/Squirrel.Mac/releases includes debug symbols.
